### ISSUE TITLE
Cannot Generate Sets

### ISSUE THREAD

**Issue by MadDoctorTolliver** [ForOhForError/Yet-Another-Magic-Card-Recognizer#7]
Neither the Bulk Generate nor the Single Set download options will generate a .yam file. The error log for each set appears as such:

java.io.FileNotFoundException: E:\Desktop\YamCR\setdata\pip_.yam (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at RecognitionStrategy.writeOut(RecognitionStrategy.java:74)
	at SetGenerator.generateSet(SetGenerator.java:138)
	at SetSelectNode.download(SetSelectNode.java:82)
	at SetLoadPanel$2.run(SetLoadPanel.java:265)

Even with previously generated sets, the program would not rewrite old .yam files. Please let me know if there is any other information needed from my end to sort this out, or if I'm just being an idiot and missing something obvious like folder permissions.

**Comment by MadDoctorTolliver** [comment]
A reinstall fixed the issue. Apologies for the unnecessary issue.
